### ISSUE TITLE
Слэш в длинных фразах

### ISSUE THREAD

**Issue by mihailtugushev** [podgorniy/alfred-translate#10]
С недавних пор при переводе длинных фраз появляется символ "/". Пример, во фразе no time for nonsense. В чем может быть проблема?

<img src="https://d.pr/i/i5PDee.png" alt="text" width="50%" height="50%">

**Comment by podgorniy** [comment]
Так не должно быть. Поведение у меня тоже повторяется. По свободе посмотрю в чем причины и как чинить.

**Comment by podgorniy** [comment]
Нашел и поправил проблему в плагине. Я лишний раз экранировал пробелы.

У тебя есть 2 варианта как поправить ситуацию у себя:

1. Скачать заново [workflow](https://github.com/podgorniy/alfred-translate/raw/master/Translate.alfredworkflow)
2. Убрать экранирование пробелов самостоятельно. Операцию нужно провести **для обоих "script filter"** секций.

Двойной клик по "script filter" (штука с бирюзовой окантовкой)
<img width="1103" alt="Screenshot 2020-07-13 at 21 58 23" src="https://user-images.githubusercontent.com/358975/87347986-5445b280-c554-11ea-8407-b45e0b962d11.png">

Убери галочку и жми "Save"
<img width="1103" alt="Screenshot 2020-07-13 at 21 58 41" src="https://user-images.githubusercontent.com/358975/87348071-75a69e80-c554-11ea-83c1-faa271ce7dfe.png">

**Comment by mihailtugushev** [comment]
Спасибо, все работает!
