### ISSUE TITLE
Снова перестал переводить 

### ISSUE THREAD

**Issue by kirillrybin** [podgorniy/alfred-translate#11]
В дебаг панели Alfred
```
[14:10:28.163] Translate[Script Filter] Queuing argument 'dog'
[14:10:28.739] Translate[Script Filter] Script with argv '(null)' finished
[14:10:28.743] ERROR: Translate[Script Filter] Code 1: Traceback (most recent call last):
  File "./translate.py", line 160, in <module>
    print get_output(sys.argv[1])
  File "./translate.py", line 134, in get_output
    responses = pool.map(process_response_as_json, requestsUrls)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: 'HTTPError()'. Reason: 'TypeError("can't pickle _ssl._SSLSocket objects",)'
```
В терминале: 
```
python -V
Python 2.7.16
```

**Comment by podgorniy** [comment]
Вижу проблему, у меня тоже воспроизводится. Что-то изменилось после обновления макоси до 10.15.6. По свободе займусь решением.

**Comment by kirillrybin** [comment]
@podgorniy у меня версия macOS 10.14.6

**Comment by 097115** [comment]
@podgorniy это со стороны Гугла изменения, мне кажется (у меня, например, не менялось вообще ничего, и macOS 10.11)

**Comment by podgorniy** [comment]
@097115, это уже интереснее. Значит дело не в версии. Спасибо, этот коммент сэкономил мне времени.

В расширении используется API яндекса, довольно старое (7+ лет), может они что-то поменяли. Зато бесплатное в отличии от гуглового. Ковырну в эту сторону тоже. Дело точно не в укро-российских блокировках, потому что из-за границ у меня тоже проблемы.

**Comment by kirillrybin** [comment]
Попробовал сделать запрос к сервису напрямую с данными из py скрипта. 
Получил такой ответ 😢:
```
{
    "code": 408,
    "message": "Maximum monthly translated text volume exceeded"
}

```

**Comment by mihailtugushev** [comment]
Яндекс предлагает купить:

> Чтобы воспользоваться сервисом Яндекс.Облако, используйте эту ссылку: 
> https://cloud.yandex.ru/docs/translate/ 
> После регистрации вам будет доступен грант, который позволит бесплатно протестировать возможности нашего API. 
> 
> Если вы физическое лицо и не являетесь резидентом РФ, используйте платную версию API Яндекс.Переводчика: 
> https://translate.yandex.ru/developers/account

Нв других форумах пишут, что они дают типа купона на 6000 р. для пользования сервисом. Но я пока не нашел.

**Comment by w201** [comment]
Может переделать на google translate?

**Comment by podgorniy** [comment]
У меня какая-то "колбаса" с яндекс аккаунтом: не могу ни оплатить доступ к API, ни привязать карту к аккаунту. Разбирательство займет неизвестно сколько времени. Не факт что я захочу платить столько сколько того потребует сервис (по статистике яндекса набегает до 45 баксов в месяц). Решение не принял, буду думать.

А пока **если хотите получить работающую версию переводчика,** замените мои ключи доступа к API на собственные. Для этого получите ключи к [translate API](https://tech.yandex.com/translate/) и [dictionary API](https://tech.yandex.com/dictionary/). Потом в альфреде в списке workflow в контекстном меню на `Translate` кликните на "Show in finder"

<img width="567" alt="Screenshot 2020-08-19 at 08 28 46" src="https://user-images.githubusercontent.com/358975/90600424-d336a680-e1f6-11ea-957b-0c96f0698fbc.png">

откройте файл `translate.py`

<img width="349" alt="Screenshot 2020-08-19 at 08 29 15" src="https://user-images.githubusercontent.com/358975/90600473-e6497680-e1f6-11ea-9fca-04e5611ed516.png">

и замените ключи в строках 11 и 12.

<img width="955" alt="Screenshot 2020-08-19 at 08 29 33" src="https://user-images.githubusercontent.com/358975/90600505-f7928300-e1f6-11ea-9a99-b88b3b61bd9a.png">

Этот же файл в этом репозитории: https://github.com/podgorniy/alfred-translate/blob/master/src/translate.py#L11

**Comment by mihailtugushev** [comment]
Получил купон на 4к на два месяца. Но так и не понял, как получить API. По всем ссылкам перебрасывается на страницу Облака. У кого-нибудь получилось?

**Comment by bolshakov** [comment]
А как использовать свои ключи, если

> We no longer issue free keys for the Yandex.Translate API. For all existing free keys, there will be a limit of 50,000 symbols as of July 31st and these keys will stop working on August 15th.

**Comment by 097115** [comment]
> Может переделать на google translate?

вроде выглядит несложно: https://stackabuse.com/text-translation-with-google-translate-api-in-python/

**Comment by podgorniy** [comment]
> А как использовать свои ключи, если

Извините, я упустил этот момент. @bolshakov

**Comment by grivachev** [comment]
Я не программист, но обожаю этот воркфлоу — считаю его одним из двух-трех, ради которых стоит £45 за lifetime Alfred subscription. Еще очень уважаю коммьюнити прогеров за свободный обмен информацией и невероятную готовность помочь, вы — крутые.

Уже неработающая версия переводчика была близка к идеальной; гугловская и Linguee альтернативы работают ощутимо медленнее и выдают только один перевод, без вариантов, а это очень важно (но все равно большое спасибо @ww7 , пока попробуем) — я даже иногда использовал ваш переводчик как словарь русских синонимов. Готов донатить @podgorniy на платный API, если до этого дойдет. Пока сохраню эту страницуу в закладки.

Бтв, яндекс что-то писал про старую версию апи (без нейронок), может ее просто как-то оставить?

**Comment by podgorniy** [comment]
**TLDR** плагин будет долго не работать (больше месяца), и новую версию гарантированно нужно будет переустанавливать.

Быстро починить ключи с помощью денег не получается: яндекс не может принимать у меня оплату как нерезидента РФ. Как резидента тоже не может (вернее эта опция отключена, но поддержка мне не включит ее из-за резиденства). Для нерездиентов и нужен айдишник регистрации компании, чего у меня нет.  Создание новых аккаунтов не дает желаемого результата, общение с поддержкой сводится к "создайте новый аккаунт".

Google translate не принимает дебетовые карты к оплате. Ради них кредитку заводить не собираюсь.

Есть вариант перевода через Azure (и мою карточку они принимают). Но их API имеет чуть другой подход чем тот, которым я пользовался: они активно используют хедеры, а код написан с расчетом на передачу параметров. Получается нужно переписывать куски кода. И становится вопрос а не перписать ли все на третий питон ибо двойка ушла в режим поддержки, и не известно как скоро второй питон выпилят из макоси.

Бонусом к этому набору факторов у меня сейчас мало времени (новая работа, ребенок, нужно подсоблять по дому), поэтому переписывание проект быстро не получится. Уйдет месяц по млим пессимистичным оценкам.

Но я гарантированно запилю новую версию. Потому что самому неудобно без переводчика, да и близкие им тоже пользуются. Сейчас думаю над дополнительными финтифлюшками (как перевод на 2 языка одновременно, сохранение истории переводов в файл итд). Если есть идеи-пожелания - напишите их в тикете по ссылке https://github.com/podgorniy/alfred-translate/issues/12.

@grivachev, очень приятны твои слова. Напиши на podgorniy.d@gmail.com как с тобой лучше связаться, я дам знать когда выйдет новая версия.

Меня можно поблагодарить за работу через патреон  https://www.patreon.com/podgorniy

**Comment by podgorniy** [comment]
@fantomnotabene я не против, выкладывайте с ссылкой и всем положеным.

**Comment by liquid245** [comment]
@podgorniy Большое спасибо за ваш плагин. Не особо замечал его раньше, когда он просто работал, но как только перестал - почувствовал боль утраты) Независимо от того, какая судьба постигнет проект:

Огромное спасибо за отличный проект и за наше сэкономленное им время!!!!)

**Comment by a-shcherba** [comment]
@podgorniy Так же хочу выразить вам большую благодарность, спасибо вам.

**Comment by bolshakov** [comment]
Я правильно понимаю, что яндекс закрыл доступ к АПИ и никакой алтернативы к нему не предоставляет?

**Comment by kirillrybin** [comment]
> Я правильно понимаю, что яндекс закрыл доступ к АПИ и никакой алтернативы к нему не предоставляет?

Только платная альтернатива yandex translate https://cloud.yandex.ru/services/translate
С знанием языка python можно за вечер прикрутить этот api к текущему workflow.

**Comment by denisborovikov** [comment]
Всем привет. В первую очередь, спасибо @podgorniy за отличный воркфлоу! Как заметили выше,  пока он работал, даже не обращал на него внимание, как только перестал - как без рук.

Я полез посмотреть, как устроен код и увидел, что воркфлоу использует под капотом 3 API:
- Yandex Translate, собственно он и перестал работать
- Yandex Dictionary - словари с транскрипцией
- Yandex Speller - проверка опечаток

В моем случае, я в 99% случаев использую воркфлоу только для перевода отдельных слов, поэтому функционал Yandex Dictionary для меня именно то что нужно. И он все еще работает. Поэтому все что нужно чтобы пофиксить воркфлоу по быстрому - это убрать запрос к API Yandex Translate, который все крашит.

Я не знаю python, поэтому мог что-то накосячить, но вот мой PR с исправлением https://github.com/podgorniy/alfred-translate/pull/13

Вы можете самостоятельно внести эти изменения или подождать, если @podgorniy сочтет эти изменения достойными чтобы вмержить в мастер.

**Comment by podgorniy** [comment]
Это шикарный PR, @denisborovikov. Спасибо большой что потратил время. Я все проверил, вмержил, сэкспортил. Новая версия работает, скачать как всегда по этой ссылке: https://github.com/podgorniy/alfred-translate/raw/master/Translate.alfredworkflow
