### ISSUE TITLE
Чего вам не хватало в работающем плагине?

### ISSUE THREAD

**Issue by podgorniy** [podgorniy/alfred-translate#12]
Хочу собрать и обсудить ваши пожелания чтобы попробовать интегрировать их в новую версию

**Comment by becauseim** [comment]
Привет! Только установил, не работает (судя по всему, чинится), поэтому, не знаю, умеет или нет, но хотелось бы иметь возможность переводить набранный текст, а не только выводить его на экран с возможностью скопировать. То есть по заданному сочетанию клавиш заменять выделенный набранный текст на переведенный. Похожее реализовано [https://github.com/voldmar/alfred-typograf?files=1](здесь)

**Comment by becauseim** [comment]
Так же можно добавить перевод текста из изображения. [Этот](https://github.com/ramiroaraujo/alfred-screenshot-ocr-workflow) воркфлоу хорошо определяет латиницу. Не знаю, можно ли научить его определять кириллицу.

**Comment by becauseim** [comment]
И сразу вопрос/пожелание: умеет ли воркфлоу проверять наличие обновлений при обращении к нему? Если нет, то хотелось бы внедрить, чтобы всегда иметь актуальную рабочую версию, а если имеются временные проблемы со стороны сервиса, выводить сообщение, что воркфлоу временно не работает.

**Comment by becauseim** [comment]
Так же можно добавить опцию переключения сервиса для перевода между гуглом и яндексом. Гугл-версия воркфлоу [@fantomnotabene](https://github.com/fantomnotabene/Alfred-GTranslator-workflow) на данный момент работает.

**Comment by skazhikadyadya** [comment]
Привет! Я или так и не разобрался, или из-за ограничений API воркфлау не может переводить фразы целиком. :(

**Comment by podgorniy** [comment]
@skazhikadyadya, API который позволял переводить фразы целиком стал платным и ребята помогли его "выпилить". [Тут](https://github.com/podgorniy/alfred-translate/issues/11#issuecomment-680219376) я описал свою ситуацию и отношение к плагину.

**Comment by skazhikadyadya** [comment]
Поздравляю с рождением ребёнка. :)

Я, понятное дело, не в претензии, просто может быть многоуважаемое сообщество подскажет альтернативу, так как мне периодически надо переводить фразы на финском и прочих экзотических языках и желательно это делать "на лету". Если сейчас невозможно это делать с помощью данного воркфлау прекрасно, оставим его для перевода непонятных слов, но может быть можно поставить что-то ещё в альфред 4? 

Спасибо.
