### ISSUE TITLE
После перевода слова не работает курсор в активном окне Xcode

### ISSUE THREAD

**Issue by ArturRuZ** [podgorniy/alfred-translate#15]
Привет! Спасибо за плагин! На MacOS Каталина, Xcode 12.4 возникает кейс:
Открываем проект -> выбираем любой файл .swift -> Переводим слово -> После закрытия Альфреда невозможно поставить курсор в проекте, до тех пор пока не кликнуть на рабочем столе.

**Comment by podgorniy** [comment]
Привет. Дело точно не в плагине потому что он использует запускается альфредом и использует его АПИ (а не апи операционки). Что-то или с xcod-ом или с alfred. Помочь тут не могу.

**Comment by ArturRuZ** [comment]
Действительно, проблема с любым плагином. Спасибо!
