### ISSUE TITLE
Не переводит фразы

### ISSUE THREAD

**Issue by notaton** [podgorniy/alfred-translate#18]
Добрый день! Во-первых, огромное спасибо автору за замечательный Workflow)
Вопрос - отдельные слова переводит замечательно, но вот с фразами проблемы. Даже фразы из 2 слов переводить отказывается. Запись лога https://cln.sh/1Qeo88

**Comment by podgorniy** [comment]
Добрый. Спасибо за добрые слова, мне приятно что работа оценена.

TLDR: это ограничение апи, и я ничего с этим делать не буду (простого решения нет).

Ограничение перевода фраз идет от ограничения используемых апи. Я использую яндексовские апи, и около года тому они изменили условия для бесплатной версии так что я не могу ее использовать даже при оплате (нужно открывать фирму). Мне осталось доступным только апи словаря, поэтому фразы не переводятся.

---

Воспользуюсь моментом общения и поделюсь мыслями.

У меня есть идея новой версии воркфлоу и даже некоторые наработки. Фишки типа перевода на несколько языков, аналитика, словарь, конечно же существующий функционал. Но эту тему без оплаты не провернуть: апи которые я хотел бы использовать небесплатны. 

Как думаешь, платил бы ты за использование воркфлоу? Каких фич тебе не хватает?

**Comment by notaton** [comment]
Добрый день) 
Платил бы я за подобного рода Workflow - да, однозначно. В работе я постоянно использую этот Workflow. Наверное одной из главных фич, которых действительно нехватает - это перевод фраз. То есть выделил фразу в любом месте, и по hotkey открылся альфред уже с переводом. По скромным подсчетам конкретно мне это бы сэкономило минут по 15 каждый день.
Так же полезной бы оказалась фича быстрого добавления фразы (слова) в избранное. Что-то типо сниппетов Alfred, только отдельно. У меня например часто есть проблемы с запоминанием того как пишутся некоторые слова и в таком случае я делаю следующее - пишу t "слово на русском" и потом копирую его перевод. Было бы очень круто, если бы я вводил ts "ne" и он мне из списка выкидывал слово "necessary". Ну и наоборот - я скопировал какое-то слово или фразу по хоткею добавил его в свой словарь.
Думаю что это не полный список)
