### ISSUE TITLE
New Yosemite-like icon

### ISSUE THREAD

**Issue by PazzaVlad** [podgorniy/alfred-translate#2]
Hi) Thanks for your workflow it's very useful for me! 

I've find more Yosemite-like stylish icon, and I think it looks great :) Maybe you want to update the old one)

This is how it looks: 
<img width="733" alt="screen shot 2015-07-18 at 4 21 24 pm" src="https://cloud.githubusercontent.com/assets/7755205/8761741/c0ce48fa-2d69-11e5-8524-1198a48f1323.png">

And the icon itself:
![icon](https://cloud.githubusercontent.com/assets/7755205/8761757/65a9beae-2d6a-11e5-932f-cb341b8ebf30.png)

**Comment by podgorniy** [comment]
Hi, Vlad.

**Comment by podgorniy** [comment]
Hi, Vlad.
I think, that having hieroglyph in ru-en/en-ru translation workflow will be confusing for users. Though I like  your icon's appearance, I would prefer to stick to current more "generic" one.

**Comment by PazzaVlad** [comment]
Thanks for answer)
May I fork your brach and do some tiny changes?)

**Comment by podgorniy** [comment]
You're welcome. Feel free.
