### ISSUE TITLE
Запуск с русской раскладки

### ISSUE THREAD

**Issue by igorkamyshev** [podgorniy/alfred-translate#6]
Доброго дня!

Спасибо за ваш труд, прекрасная утилита.

У меня появилась мысль, что при переводе с русского на английский не очень удобно вводить английскую букву "t". Может быть, добавить возможность вводить и букву "т"? Как вы на это смотрите?

**Comment by ivan-leschinsky** [comment]
@igorkamyshev Добрый день. Я просто поставил в дополнение русскую букву "е", которая там же, где и английская "t", таким образом всегда нажимаю на одно и то же место. 

Так же у меня всегда идет перевод сразу и на английски и на русский язык по одной букве "t"/"е"
![gtranslate](https://user-images.githubusercontent.com/4127186/44152801-1b0d9620-a0af-11e8-8502-844792ef8404.jpg)

**Comment by PazzaVlad** [comment]
Угу, это в самом альфреде меняется. Я поставил цифру 1 просто)

**Comment by igorkamyshev** [comment]
Да, я тоже изменил в Альфреде. Но разве не здорово было бы поставлять воркфлоу сразу с такой конфигурацией?

**Comment by podgorniy** [comment]
@ivan-leschinsky как выглядит ваш воркфлоу? 

Я не нашел решения где можно было бы добавить еще один keyword так [чтобы не понадобилось](https://www.alfredforum.com/topic/1528-multiple-keywords-for-a-single-script-filter/?do=findComment&comment=53146) нажимать еще одну клавишу после keyword. Такая необходимость вредит легкости использования воркфлоу.

Есть вариант дублировать скрипт и задавать русский keyword для копии. Выглядит ужасно и в стандартную поставку не влезет.
<img width="1052" alt="alfred_preferences" src="https://user-images.githubusercontent.com/358975/44169293-3b1bf900-a0d4-11e8-8231-ff1682312dc7.png">

@igorkamyshev рад что пользуетесь моей приблудой. Если получится добавить русский keyword, то это будет `е`. Место на клавиатуре проще запомнить чем вспоминать какую букву набирать при какой расскладке.

**Comment by igorkamyshev** [comment]
@podgorniy использую воркфлоу с несколькими ключевыми словами. При попытке экспортировать его проблем не возникло.

<img width="671" alt="screen shot 2018-08-16 at 10 05 51" src="https://user-images.githubusercontent.com/26767722/44193595-18252f80-a13c-11e8-9d35-0381921c0090.png">
