### ISSUE TITLE
Перестал переводить...

### ISSUE THREAD

**Issue by adminoid** [podgorniy/alfred-translate#7]
Вероятно, это связано с обновлением гугл переводчика

**Comment by podgorniy** [comment]
У меня продолжает работать.

Поищи проблему со своей стороны в сети. Дело может быть в файерволе, http-прокси или недоступности серверов яндекса (translate.yandex.net).

**Comment by adminoid** [comment]
Прошу прощения, если есть возможность, помогите, пожалуйста.
Переводчик вместо перевода предлагает открыть гугл амазон и т.п. с этим запросом.
Я предполагаю, что это произошло после того, как я обновил python до 3-й версии.
Точнее у меня сейчас стоит 2 версии 2 и 3
```zsh
[I] ➜ python2 --version
Python 2.7.10

~
[I] ➜ python --version
Python 3.7.1

~
```

Можно как-нибудь отдебажить ошибку питона при запуске переводчика, если она есть?
Спасибо!

**Comment by podgorniy** [comment]
Settings -> Вверху таб "Workflows" -> В левой колонке выбери воркфлоу "Translate" -> В право панели выбери даблкликом элемент с иконкой плагина (там еще подпись под иконкой "Script Filter"). В появившемся окне есть выпадающий список рядом с "Language", поиграйся с элементами в этом списке. Нужно указать путь к бинарнику версии 2.x.

<img width="766" alt="2__fish___users_dpodgorniy_work_main__fish__and_alfred_preferences" src="https://user-images.githubusercontent.com/358975/49453252-0ba80e00-f7e3-11e8-8451-79e5dc314152.png">

Если у тебя указан бинарник версии 2, то попробуй почитать логи: жми на жука, пользуся плагином, читай логи. Жук тут:
<img width="849" alt="alfred_preferences" src="https://user-images.githubusercontent.com/358975/49453349-3f833380-f7e3-11e8-9b1c-dbafe09fb9a7.png">

**Comment by adminoid** [comment]
![debugging](https://user-images.githubusercontent.com/548475/49459391-fb525c00-f7ff-11e8-8119-aac2fdaae0fc.jpg)
Вот что пишет дебаг...

**Comment by podgorniy** [comment]
Он говорит что по пути `/usr/bin/python` в твоей системе нет ни бинарника ни ссылки на бинарник питона. Этот путь важен, ибо питон по этому пути используется установщиками, сборщиками и другими программами. Почитай как сделать так чтобы были питоны двух версий, но при этом по пути `/usr/bin/python` лежал питон 2.x

**Comment by adminoid** [comment]
![bitmap](https://user-images.githubusercontent.com/548475/49469418-83dcf680-f818-11e8-8032-1d79c8274c87.jpg)
У меня сейчас так и есть, но вот дебаггер пишет то, что выше.

**Comment by podgorniy** [comment]
Значит я что-то путаю. Я в этом не разбираюсь достаточно чтобы помочь тебе. Поспрашивай на форуме альфреда. 

Я бы еще попробовал переустановать плагин заново.

**Comment by kirillrybin** [comment]
```
[00:21:48.999] Translate[Script Filter] Queuing argument 'c'
[00:21:49.124] Translate[Script Filter] Queuing argument 'ca'
[00:21:49.285] Translate[Script Filter] Queuing argument 'cat'
[00:21:49.721] Translate[Script Filter] Script with argument '(null)' finished
[00:21:49.724] ERROR: Translate[Script Filter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "translate.py", line 133, in get_output
    responses = pool.map(process_response_as_json, requestsUrls)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
urllib2.URLError: <urlopen error [Errno 54] Connection reset by peer>
```

Воркфлоу переустанавливал.
