### ISSUE TITLE
Спасибо!

### ISSUE THREAD

**Issue by mikhasev** [podgorniy/alfred-translate#9]
Дмитрий, это лучший flow для Alfred ever. Спасибо тебе огромное. 
Пользуюсь им для заполнения карточек Anki. 
Есть ли возможность сделать так, чтобы показываемый в строке Alfred перевод можно было скопировать, в идеале с транскрипцией? Чтобы сразу засунуть в словарную карточку...

**Comment by podgorniy** [comment]
Я рад что эта штука полезна.

> показываемый в строке Alfred перевод можно было скопировать, в идеале с транскрипцией?

Функционала копирования с транскрипцией нет и не планируется. А сам перевод можно скопировать. Выбери переведенный текст из списка результатов и жми `Enter`.

**Comment by podgorniy** [comment]
Я смог ответить на вопрос? Хочу закрыть этот `open issue`.
